# -*- coding: utf-8 -*-
"""task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10f-gv4Qcc5hLPeZHuLMih4PFJYAIhtHX
"""

import pandas as pd

df = pd.read_csv("/content/Mall_Customers.csv")
df

print(df.head())

print(df.shape)

print("Missing values:",df.isnull().sum())

df.dropna(how="all", inplace=True)

for col in df.select_dtypes(include="number").columns:
    df[col].fillna(df[col].median(), inplace=True)

for col in df.select_dtypes(include="object").columns:
    df[col].fillna(df[col].mode()[0], inplace=True)

df.drop_duplicates(inplace=True)

df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

if "gender" in df.columns:
    df["gender"] = df["gender"].str.strip().str.lower().replace({
        "male": "Male", "m": "Male",
        "female": "Female", "f": "Female"
    })

if "country" in df.columns:
    df["country"] = df["country"].str.title()

for col in df.columns:
    if "date" in col or "dob" in col:
        df[col] = pd.to_datetime(df[col], errors="coerce")

if "age" in df.columns:
    df["age"] = df["age"].astype("int", errors="ignore")

print("\nCleaned Shape:", df.shape)
print("\nCleaned Data Types:\n", df.dtypes)

output_file = "/mnt/data/cleaned_dataset.csv"

print(f"\nCleaned dataset saved as: {output_file}")